import{a as w,S as p,i as L}from"./assets/vendor-f51e6815.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function g(t,o){const s="42796479-140a0b0d57e5aafe2bfea6b1d",n="https://pixabay.com/api/",e="photo",r="horizontal",i="true";try{const d=await w.get(n,{params:{key:s,q:t,image_type:e,orientation:r,safesearch:i,page:o,per_page:15}}),{data:v}=d,{hits:f,totalHits:S}=v;if(!Array.isArray(f)||f.length===0)throw new Error("No images found");return{images:f,totalHits:S}}catch{throw new Error("Failed to fetch images")}}const P=document.querySelector(".gallery"),b=document.querySelector(".loader");let A=new p(".gallery a");function E(t){const o=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,downloads:i,comments:m,views:d})=>`<li class="gallery-item">
              <a href="${n}" class="gallery-link"><img class="gallery-img" src="${s}" alt="${e}" data-source="${n}" title="${e}" /></a>
              <div class="activity">
              <h3>Likes<p class="activity-item">${r}</p></h3>
              <h3>Views<p class="activity-item">${d}</p></h3>
              <h3>Comments<p class="activity-item">${m}</p></h3>
              <h3>Downloads<p class="activity-item">${i}</p></div></h3>
          </li>`).join("");P.insertAdjacentHTML("beforeend",o),A.refresh(),b.style.display="none"}function a(t){L.error({title:"Ошибка",message:t,position:"topRight"}),b.style.display="none"}const q=document.querySelector(".gallery"),$=document.querySelector("input"),I=document.querySelector("form"),u=document.querySelector(".loader-container"),l=document.querySelector(".load-more-btn"),h=document.querySelector(".load-more-loader");let c=1,y="";new p(".gallery a");function H(){const t=document.querySelector(".gallery-item");if(t){const{height:o}=t.getBoundingClientRect();return o}return 0}function M(t){t.preventDefault();const o=$.value.trim();if(o.length===0){a("Please enter a search term before searching for images.");return}y!==o&&(q.innerHTML="",l.style.display="none",c=1),y=o,u.style.display="block",g(y,c).then(s=>{const{images:n,totalHits:e}=s;if(n.length===0)throw new Error("No images found");E(n),n.length>=15&&c*15<e?l.style.display="block":(l.style.display="none",a("Извините, но вы достигли конца результатов поиска."))}).catch(s=>{console.error("Ошибка при получении изображений:",s),a("Не удалось получить изображения. Пожалуйста, попробуйте позже.")}).finally(()=>{u.style.display="none"})}function O(){u.style.display="block",h.style.display="block",c++,g(y,c).then(t=>{const{images:o,totalHits:s}=t;o.length>0?(E(o),c*15>=s?(l.style.display="none",a("We're sorry, but you've reached the end of search results.")):T(H()*3)):(l.style.display="none",a("We're sorry, but you've reached the end of search results."))}).catch(t=>{console.error("Error fetching more images:",t),a("Failed to fetch more images. Please try again later.")}).finally(()=>{u.style.display="none",h.style.display="none"})}function T(t){window.scrollBy({top:t,behavior:"smooth"})}I.addEventListener("submit",M);l.addEventListener("click",O);
//# sourceMappingURL=commonHelpers.js.map
