import{S as p,i as v}from"./assets/vendor-f3f87f24.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function g(t,o){const d=await fetch(`https://pixabay.com/api/?key=42796479-140a0b0d57e5aafe2bfea6b1d&q=${t}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=15`);if(!d.ok)throw new Error("Failed to fetch images");const m=await d.json(),S=m.hits,$=m.totalHits;return{images:S,totalHits:$}}const A=document.querySelector(".gallery"),E=document.querySelector(".loader");let P=new p(".gallery a");function b(t){const o=t.map(({webformatURL:s,largeImageURL:n,tags:e,likes:r,downloads:i,comments:f,views:d})=>`<li class="gallery-item">
              <a href="${n}" class="gallery-link"><img class="gallery-img" src="${s}" alt="${e}" data-source="${n}" title="${e}" /></a>
              <div class="activity">
              <h3>Likes<p class="activity-item">${r}</p></h3>
              <h3>Views<p class="activity-item">${d}</p></h3>
              <h3>Comments<p class="activity-item">${f}</p></h3>
              <h3>Downloads<p class="activity-item">${i}</p></div></h3>
          </li>`).join("");A.insertAdjacentHTML("beforeend",o),P.refresh(),E.style.display="none"}function l(t){v.error({title:"Ошибка",message:t,position:"topRight"}),E.style.display="none"}const w=document.querySelector(".gallery"),I=document.querySelector("input"),L=document.querySelector("form"),y=document.querySelector(".loader-container"),a=document.querySelector(".load-more-btn"),h=document.querySelector(".load-more-loader");let c=1,u="";new p(".gallery a");function q(){const t=document.querySelector(".gallery-item");if(t){const{height:o}=t.getBoundingClientRect();return o}return 0}function T(t){t.preventDefault();const o=I.value.trim();if(o.length===0){l("Please enter a search term before searching for images.");return}u!==o&&(w.innerHTML="",a.style.display="none",c=1),u=o,y.style.display="block",g(u,c).then(s=>{const{images:n,totalHits:e}=s;if(n.length===0)throw new Error("No images found");b(n),n.length>=15&&c*15<e?a.style.display="block":(a.style.display="none",l("Извините, но вы достигли конца результатов поиска."))}).catch(s=>{console.error("Ошибка при получении изображений:",s),l("Не удалось получить изображения. Пожалуйста, попробуйте позже.")}).finally(()=>{y.style.display="none"})}function H(){y.style.display="block",h.style.display="block",g(u,c).then(t=>{const{images:o,totalHits:s}=t;o.length>0?(b(o),c*15>=s?(a.style.display="none",l("We're sorry, but you've reached the end of search results.")):O(q()*3)):(a.style.display="none",l("We're sorry, but you've reached the end of search results."))}).catch(t=>{console.error("Error fetching more images:",t),l("Failed to fetch more images. Please try again later.")}).finally(()=>{y.style.display="none",h.style.display="none"}),c++}function O(t){window.scrollBy({top:t,behavior:"smooth"})}L.addEventListener("submit",T);a.addEventListener("click",H);
//# sourceMappingURL=commonHelpers.js.map
